const router = require("express").Router()
const authRouter = require("./auth.route")
const userRouter = require("./admin/user.route")
const categoryRouter = require("./admin/category.route")
const subcategoryRouter = require("./admin/subcategory.route")
const productRouter = require("./admin/product.route")
const providerRouter = require("./admin/provider.route")
const voucherRouter = require("./admin/voucher.route")
const orderRouter = require("./admin/order.route")
const storageRouter = require("./admin/storage.route")
const restockRouter = require("./admin/restock.route")
const contactRouter = require("./admin/contact.route")
const galleryRouter = require("./admin/gallery.route")
const statisticsRouter = require("./admin/statistics.route")
const profileRouter = require("./client/profile.route")
const clientProductRouter = require("./client/product.route")
const clientCartRouter = require("./client/cart.route")
const clientIndexRouter = require("./client/index.route")
const clientOrderRouter = require("./client/order.route")
const { _ensureAccessToken, _ensureAdminRole } = require("../helper/auth")

router.use(authRouter)
// Client routes
router.use(clientIndexRouter)
router.use(clientProductRouter)
router.use(clientCartRouter)
router.use("/my-orders", _ensureAccessToken, clientOrderRouter)
router.use("/profile", _ensureAccessToken, profileRouter)
// Admin routes
router.use("/admin/users", _ensureAccessToken, _ensureAdminRole, userRouter)
router.use("/admin/categories", _ensureAccessToken, _ensureAdminRole, categoryRouter)
router.use("/admin/subcategories", _ensureAccessToken, _ensureAdminRole, subcategoryRouter)
router.use("/admin/products", _ensureAccessToken, _ensureAdminRole, productRouter)
router.use("/admin/providers", _ensureAccessToken, _ensureAdminRole, providerRouter)
router.use("/admin/vouchers", _ensureAccessToken, _ensureAdminRole, voucherRouter)
router.use("/admin/orders", _ensureAccessToken, _ensureAdminRole, orderRouter)
router.use("/admin/storages", _ensureAccessToken, _ensureAdminRole, storageRouter)
router.use("/admin/restocks", _ensureAccessToken, _ensureAdminRole, restockRouter)
router.use("/admin/contacts", _ensureAccessToken, _ensureAdminRole, contactRouter)
router.use("/admin/gallery", _ensureAccessToken, _ensureAdminRole, galleryRouter)
router.use("/admin/statistics", _ensureAccessToken, _ensureAdminRole, statisticsRouter)

module.exports = router